"""empty message

Revision ID: cf91a29ef785
Revises: 2a748d822728
Create Date: 2022-12-06 21:02:23.232621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf91a29ef785'
down_revision = '2a748d822728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drink', schema=None) as batch_op:
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('flavor',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drink', schema=None) as batch_op:
        batch_op.alter_column('flavor',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('brand',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###
